CREATE TABLE IF NOT EXISTS submissions (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255),
    user_id VARCHAR(255),
    taxpayer_id VARCHAR(50),
    tax_year INTEGER,
    status VARCHAR(255) NOT NULL,
    auditor_comments TEXT,
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by VARCHAR(255),
    return_type VARCHAR(50),
    tax_due DOUBLE PRECISION,
    taxpayer_name VARCHAR(255),
    taxpayer_fein VARCHAR(50),
    priority VARCHAR(20),
    risk_score INTEGER,
    has_discrepancies BOOLEAN,
    discrepancy_count INTEGER,
    rejection_reason TEXT,
    digital_signature VARCHAR(512),
    gross_receipts DOUBLE PRECISION,
    net_profit DOUBLE PRECISION,
    filed_date TIMESTAMP,
    due_date DATE
);
