-- Flyway Migration V25: Create penalty_abatements table for reasonable cause abatement requests
--
-- Functional Requirements:
-- FR-033 to FR-039: Penalty abatement request, review, and approval workflow
--
-- Multi-tenant isolation per Constitution II

CREATE TABLE IF NOT EXISTS penalty_abatements (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    return_id UUID NOT NULL,
    penalty_id UUID, -- NULL if requesting abatement for all penalties
    
    -- Request details
    request_date DATE NOT NULL,
    abatement_type VARCHAR(50) NOT NULL CHECK (abatement_type IN ('LATE_FILING', 'LATE_PAYMENT', 'ESTIMATED', 'ALL')),
    requested_amount DECIMAL(15,2) NOT NULL CHECK (requested_amount >= 0),
    
    -- Reason for abatement
    reason VARCHAR(50) NOT NULL CHECK (reason IN ('DEATH', 'ILLNESS', 'DISASTER', 'MISSING_RECORDS', 'ERRONEOUS_ADVICE', 'FIRST_TIME', 'OTHER')),
    explanation TEXT,
    supporting_documents JSONB,
    
    -- Review and decision
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'PARTIAL', 'DENIED', 'WITHDRAWN')),
    reviewed_by UUID,
    review_date DATE,
    approved_amount DECIMAL(15,2) CHECK (approved_amount >= 0),
    denial_reason TEXT,
    
    -- Form generation
    form_generated VARCHAR(500), -- Form 27-PA PDF path
    
    -- Audit trail
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    
    -- Constraints
    CONSTRAINT check_approved_amount CHECK (
        (status NOT IN ('APPROVED', 'PARTIAL')) OR 
        (approved_amount IS NOT NULL AND approved_amount > 0)
    ),
    CONSTRAINT check_denial_reason CHECK (status != 'DENIED' OR denial_reason IS NOT NULL),
    CONSTRAINT check_review_fields CHECK (
        status = 'PENDING' OR 
        (reviewed_by IS NOT NULL AND review_date IS NOT NULL)
    ),
    CONSTRAINT check_approved_vs_requested CHECK (approved_amount IS NULL OR approved_amount <= requested_amount),
    CONSTRAINT fk_penalty_abatement_penalty FOREIGN KEY (penalty_id) REFERENCES penalties(id) ON DELETE SET NULL
);

-- Create indexes
CREATE INDEX idx_abatement_return ON penalty_abatements(return_id);
CREATE INDEX idx_abatement_penalty ON penalty_abatements(penalty_id);
CREATE INDEX idx_abatement_status ON penalty_abatements(status);
CREATE INDEX idx_abatement_reason ON penalty_abatements(reason);
CREATE INDEX idx_abatement_reviewed_by ON penalty_abatements(reviewed_by);

-- Comments
COMMENT ON TABLE penalty_abatements IS 'Stores penalty abatement requests for reasonable cause';
COMMENT ON COLUMN penalty_abatements.reason IS 'Reason: DEATH, ILLNESS, DISASTER, MISSING_RECORDS, ERRONEOUS_ADVICE, FIRST_TIME, OTHER';
COMMENT ON COLUMN penalty_abatements.status IS 'Status: PENDING, APPROVED, PARTIAL, DENIED, WITHDRAWN';
COMMENT ON COLUMN penalty_abatements.form_generated IS 'Path to Form 27-PA PDF generated by pdf-service';
